### ISSUE TITLE
Práctica 1_Mejora DRS

### ISSUE THREAD

**Issue by yanet02** [SistemasTecTlaxiaco/actividad-2-practica-de-validacion-de-documento-y-proyecto-equipo-ycee#2]
[Práctica 1_Mejora DRS..pdf](https://github.com/SistemasTecTlaxiaco/actividad-2-practica-de-validacion-de-documento-y-proyecto-equipo-ycee/files/14314564/Practica.1_Mejora.DRS.pdf)

**Comment by ka194** [comment]
20/20
BUEN TRABAJO

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
